export default {
  SYS_USER_LOGIN: {
    url: '/system/security/login',
    method: 'POST',
    desc: '',
    auth: '',
  },
  BD_SCHEMA: {
    url: '/fsc/budget/budgetSchema/list',
    method: 'POST',
    auth: 'huangh',
    desc: '预算方案',
    mockhandler: 'list',
    mocktable: 'FSC_BD_SCHEMA_LIST',
  },
  BD_SCHEMA_GETONE: {
    url: '/fsc/budget/budgetSchema/querySchemaByBdUnitId',
    method: 'GET',
    auth: 'xia_zhh',
    desc: '查询预算单元所属的预算方案',
    mockhandler: 'list',
    mocktable: 'FSC_BD_SCHEMA_LIST',
  },
  BD_SCHEMA_AUDITONE: {
    url: '/fsc/budget/expenseAdjust/auditOne',
    method: 'POST',
    auth: 'xia_zhh',
    desc: '预算调整的审批',
  },
  // 借款
  CLAIM_ECLOAN_ADDINIT: {
    url: '/fsc/claim/ecLoan/addInit',
    method: 'POST',
    auth: 'zhaoran',
    desc: '借款新增初始化',
  },
  CLAIM_ECLOAN_EDITINIT: {
    url: '/fsc/claim/ecLoan/editRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '借款修改初始化',
  },
  CLAIM_ECLOAN_SAVE: {
    url: '/fsc/claim/ecLoan/saveOrUpdateEcLoan',
    method: 'POST',
    auth: 'zhaoran',
    desc: '借款保存',
  },
  CLAIM_ECLOAN_SUBMIT: {
    url: '/fsc/claim/ecLoan/submitRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '借款提交',
  },
  // 还款
  CLAIM_ECPAYOFF_ADDINIT: {
    url: '/fsc/claim/ecPayoff/addInit',
    method: 'POST',
    auth: 'zhaor',
    desc: '还款新增初始化',
    mockhandler: 'getone',
  },
  CLAIM_ECPAYOFF_RETURNSTYLE: {
    url: '/system/lookup/getMdPaymentModes',
    method: 'GET',
    auth: 'zhaor',
    desc: '还款方式查询服务',
  },
  CLAIM_ECPAYOFF_EDITINIT: {
    url: '/fsc/claim/ecPayoff/editInit',
    method: 'POST',
    auth: 'zhaoran',
    desc: '还款修改初始化',
    mockhandler: 'getone',
  },
  CLAIM_ECPAYOFF_SAVE: {
    url: '/fsc/claim/ecPayoff/saveOrUpdateByDto',
    method: 'POST',
    auth: 'zhaor',
    desc: '还款保存方法',
    mockhandler: 'saveorupdate',
  },
  CLAIM_ECPAYOFF_SUBMIT: {
    url: '/fsc/claim/ecPayoff/submitClaim',
    method: 'POST',
    auth: 'zhaor',
    desc: '还款提交方法',
    mockhandler: 'saveorupdate',
  },
  // 业务招待费
  CLAIM_ECENTERTAIN_ADDINIT: {
    url: '/fsc/claim/ecentertain/addInit',
    method: 'POST',
    auth: 'zhaor',
    desc: '业务招待费新增初始化',
  },
  CLAIM_ECENTERTAIN_EDITINIT: {
    url: '/fsc/claim/ecentertain/editRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '业务招待费修改初始化',
  },
  CLAIM_ECENTERTAIN_SAVE: {
    url: '/fsc/claim/ecentertain/saveOrUpdateRecord',
    method: 'POST',
    auth: 'zhaor',
    desc: '业务招待费保存',
  },
  CLAIM_ECENTERTAIN_SUBMIT: {
    url: '/fsc/claim/ecentertain/submitClaim',
    method: 'POST',
    auth: 'zhaor',
    desc: '业务招待费提交',
  },
  // 私车公用
  CLAIM_MILEAGESTAND_LIST: {
    url: '/fsc/base/bcPrivateCarStandard/selectPageOrderMap',
    method: 'GET',
    auth: 'zhaoran',
    desc: '私车公用',
    mockhandler: 'list',
    mocktable: 'CLAIM_MILEAGESTAND_LIST',
  },
  CLAIM_MILEAGESTAND_DEL: {
    url: '/fsc/base/bcPrivateCarStandard/deleteMulti',
    method: 'delete',
    auth: 'zhaoran',
    desc: '私车公用',
    mockhandler: 'delete',
    mocktable: 'CLAIM_MILEAGESTAND_LIST',
  },
  CLAIM_MILEAGESTAND_GETONE: {
    url: '/fsc/base/bcPrivateCarStandard/getOne',
    method: 'GET',
    auth: 'zhaoran',
    desc: '私车公用',
    mockhandler: 'getone',
    mocktable: 'CLAIM_MILEAGESTAND_LIST',
  },
  CLAIM_MILEAGESTAND_SAVE: {
    url: '/fsc/base/bcPrivateCarStandard/saveOrUpdate',
    method: 'POST',
    auth: 'zhaoran',
    desc: '私车公用',
    mockhandler: 'saveOrUpdate',
    mocktable: 'CLAIM_MILEAGESTAND_LIST',
  },

  // 通讯费定额标准
  EC_PHONE_LIST: {
    url: '/fsc/base/bcTelphoneQuotaStandard/selectPageOrderMap',
    method: 'GET',
    auth: 'zhaoran',
    desc: '通讯费定额标准列表查询',
    mockhandler: 'list',
    mocktable: 'FSC_EC_PHONE_LIST',
  },
  EC_PHONE_GETONE: {
    url: '/fsc/base/bcTelphoneQuotaStandard/getOne',
    method: 'GET',
    auth: 'zhaoran',
    desc: '通讯费定额标准记录修改',
    mockhandler: 'getOne',
    mocktable: 'FSC_EC_PHONE_LIST',
  },
  EC_PHONE_DEL: {
    url: '/fsc/base/bcTelphoneQuotaStandard/deleteMulti',
    method: 'delete',
    auth: 'zhaoran',
    desc: '通讯费定额标准记录删除',
    mockhandler: 'deleteItem',
    mocktable: 'FSC_EC_PHONE_LIST',
  },
  EC_PHONE_SAVE: {
    url: '/fsc/base/bcTelphoneQuotaStandard/saveOrUpdate',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通讯费定额标准记录删除',
    mockhandler: 'saveOrUpdate',
    mocktable: 'FSC_EC_PHONE_LIST',
  },
  FSC_IMAGE: {
    url: '/exif/client/image/viewImage',
    method: 'POST',
    auth: 'zhaoran',
    desc: '查看影像服务地址',
  },
  // 出差计划、出差申请单
  EA_TRAVEL_ADDINIT: {
    url: '/fsc/ea/eaOrderTravelplan/addInit',
    method: 'GET',
    auth: 'zhaoran',
    desc: '出差申请单新增初始化',
  },
  EA_TRAVEL_EDITINIT: {
    url: '/fsc/ea/eaOrderTravelplan/editInit',
    method: 'GET',
    auth: 'zhaoran',
    desc: '出差申请单修改',
  },
  EA_TRAVEL_EDITINITBYID: {
    url: '/fsc/ea/eaOrderTravelplan/editInitByDocId',
    method: 'GET',
    auth: 'zhaoran',
    desc: '出差申请单通过id查询单据数据-wennn专用',
  },
  EA_TRAVEL_GETONE: {
    url: '/fsc/ea/eaOrderTravelplan/getOne',
    method: 'GET',
    auth: 'zhaoran',
    desc: '出差申请单修改',
  },
  EA_TRAVEL_SAVE: {
    url: '/fsc/ea/eaOrderTravelplan/saveOrUpdate',
    method: 'POST',
    auth: 'zhaoran',
    desc: '出差单保存',
  },
  EA_TRAVEL_SUBMIT: {
    url: '/fsc/ea/eaOrderTravelplan/submitRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '出差申请单提交',
  },
  // 对公费用事前申请单
  EA_GENERALAPPLY_ADDINIT: {
    url: '/fsc/ea/eaApplyGeneral/addInit',
    method: 'GET',
    auth: 'zhaoran',
    desc: '对公费用和资产采购事前申请单新增初始化',
    mockhandler: 'getOne',
    mocktable: 'FSC_APPLY_PUBLICEXPENSE_LIST',
  },
  EA_GENERALAPPLY_EDITINIT: {
    url: '/fsc/ea/eaApplyGeneral/editInit',
    method: 'GET',
    auth: 'zhaoran',
    desc: '对公费用和资产采购事前申请单修改初始化',
    mockhandler: 'getOne',
    mocktable: 'FSC_APPLY_PUBLICEXPENSE_LIST',
  },
  EA_GENERALAPPLY_SAVE: {
    url: '/fsc/ea/eaApplyGeneral/saveOrUpdate',
    method: 'POST',
    auth: 'zhaoran',
    desc: '对公费用和资产采购事前申请单保存',
    mockhandler: 'saveOrUpdate',
    mocktable: 'FSC_APPLY_PUBLICEXPENSE_LIST',
  },
  EA_GENERALAPPLY_SUBMIT: {
    url: '/fsc/ea/eaApplyGeneral/submitRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '对公费用和资产采购事前申请单提交',
  },
  // 资产采购事前申请单
  EA_ASSETS_ADDINIT: {
    url: '/fsc/ea/eaApplyAssets/addInit',
    method: 'GET',
    auth: 'zhaoran',
    desc: '对公费用和资产采购事前申请单新增初始化',
    mockhandler: 'getOne',
    mocktable: 'FSC_APPLY_PUBLICEXPENSE_LIST',
  },
  EA_ASSETS_EDITINIT: {
    url: '/fsc/ea/eaApplyAssets/editInit',
    method: 'GET',
    auth: 'zhaoran',
    desc: '对公费用和资产采购事前申请单修改初始化',
    mockhandler: 'getOne',
    mocktable: 'FSC_APPLY_PUBLICEXPENSE_LIST',
  },
  EA_ASSETS_SAVE: {
    url: '/fsc/ea/eaApplyAssets/saveOrUpdate',
    method: 'POST',
    auth: 'zhaoran',
    desc: '对公费用和资产采购事前申请单保存',
    mockhandler: 'saveOrUpdate',
    mocktable: 'FSC_APPLY_PUBLICEXPENSE_LIST',
  },
  EA_ASSETS_SUBMIT: {
    url: '/fsc/ea/eaApplyAssets/submitRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '对公费用和资产采购事前申请单提交',
  },
  // 申请单待我审批
  EA_APPLYGENERAL_AUDIT_LIST: {
    url: '/fsc/ea/eaApplyGeneral/queryMyHandleTask',
    method: 'GET',
    auth: 'zhaoran',
    desc: '事前申请单待我审批列表查询',
  },
  EA_APPLYGENERAL_AUDIT: {
    url: '/fsc/ea/eaApplyGeneral/batchAuditMulti',
    method: 'POST',
    auth: 'zhaoran',
    desc: '对公费用事前申请单通过',
  },
  EA_APPLYTREAVEL_AUDIT: {
    url: '/fsc/ea/eaOrderTravelplan/batchAuditMulti',
    method: 'POST',
    auth: 'zhaoran',
    desc: '出差申请单通过',
  },
  EA_GENERALAPPLY_GETONE: {
    url: '/system/rc/rcFlowHandleUrl/getHandleUrl',
    method: 'POST',
    auth: 'zhaoran',
    desc: '对公费用事前申请单修改',
    mockhandler: 'getOne',
    mocktable: 'FSC_APPLY_PUBLICEXPENSE_LIST',
  },
  // 申请单已办
  EA_APPLYGENERAL_AUDITED_LIST: {
    url: '/fsc/ea/eaApplyGeneral/queryMyHandleHistory',
    method: 'GET',
    auth: 'zhaoran',
    desc: '申请单已办列表查询',
  },
  // 申请单列表
  EA_GENERALAPPLY_LIST: {
    url: '/fsc/ea/eaApplyGeneral/queryViewApplyAdvance',
    method: 'GET',
    auth: 'zhaoran',
    desc: '申请单列表查询',
  },
  // 申请单草稿箱1207
  EA_GENERALAPPLY_LIST_DRAFT: {
    url: '/fsc/ea/eaApplyGeneral/queryViewApplyAdvanceForDraft',
    method: 'GET',
    auth: 'zhaoran',
    desc: '申请单草稿箱',
  },
  // 申请单追踪
  EA_GENERALAPPLY_TRACE: {
    url: '/fsc/ea/eaApply/searchListForDto',
    method: 'GET',
    auth: 'zhaoran',
    desc: '申请单追踪查询',
  },
  // 申请单追踪查询数据
  EA_GENERALAPPLY_TRACE_FINDRECORD: {
    url: '/fsc/ea/eaApply/findRecord',
    method: 'GET',
    auth: 'zhaoran',
    desc: '申请单追踪点击单据号查询数据',
  },
  // 申请单历史追踪查询数据
  EA_APPLY_HISTORY_TRACE: {
    url: '/fsc/ea/eaApply/queryHistoricalTracing',
    method: 'GET',
    auth: 'zhaoran',
    desc: '申请单历史追踪查询数据',
  },
  // 申请单执行追踪查询数据
  EA_APPLY_EXECUTION_TRACE: {
    url: '/fsc/ea/eaApply/queryClaimExecutionTracking',
    method: 'GET',
    auth: 'zhaoran',
    desc: '申请单执行追踪查询数据',
  },
  EA_GENERALAPPLY_DEL: {
    url: '/fsc/ea/eaApply/deleteMultiClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '对公费用事前申请单草稿箱删除',
  },
  EA_GENERALAPPLY_INVALID: {
    url: '/fsc/ea/eaApply/invalidClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '对公费用事前申请单草稿箱作废',
  },
  // 我的申请单
  EA_MY_APPLY: {
    url: '/fsc/ea/eaApplyGeneral/queryMyApplyList',
    method: 'GET',
    auth: 'zhaoran',
    desc: '我的申请单',
  },
  // 我的申请单资产采购申请单撤回方法
  EA_ASSET_CALLBACK: {
    url: '/fsc/ea/eaApplyGeneral/undoTaskRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '我的申请单撤回方法',
  },
  // 我的申请单出差申请撤回方法
  EA_TRAVEL_CALLBACK: {
    url: '/fsc/ea/eaOrderTravelplan/undoTaskRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '我的申请单撤回方法',
  },
  // 精确权限查询方法
  PRECISE_PERMISSION_QUERY: {
    url: '/system/ad/adUserDataPri/getAdUserDataPriRuleListDto',
    method: 'POST',
    auth: 'zhaoran',
    desc: '精确权限查询方法',
  },
  // 模糊权限查询方法
  FUZZY_PRECISE_QUERY: {
    url: '/system/ad/adUserDataPri/getAdUserDataPriRuleList',
    method: 'POST',
    auth: 'zhaoran',
    desc: '模糊权限查询方法',
  },
  // 报账单审批通过退回方法
  CLAIM_AUDIT: {
    url: '/fsc/claim/ecClaimApprove/approveClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '报账单审批通过退回方法',
  },
  // 通用报账单
  CLAIM_DAILY_ADDINIT: {
    url: '/fsc/claim/ecdaily/addInit',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通用报账单新增初始化',
  },
  CLAIM_DAILY_EDITINIT: {
    url: '/fsc/claim/ecdaily/editRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通用报账单修改初始化',
  },
  CLAIM_DAILY_SUBMIT: {
    url: '/fsc/claim/ecdaily/submitClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通用报账单提交',
  },
  CLAIM_DAILY_SAVE: {
    url: '/fsc/claim/ecdaily/saveClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通用报账单保存',
  },
  // 通讯费报账单
  CLAIM_PHONE_ADDINIT: {
    url: '/fsc/claim/ecPhone/addInit',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通讯费报账单新增初始化',
  },
  CLAIM_PHONE_EDITINIT: {
    url: '/fsc/claim/ecPhone/editRecord',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通讯费报账单修改初始化',
  },
  CLAIM_PHONE_SUBMIT: {
    url: '/fsc/claim/ecPhone/submitClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通讯费报账单提交',
  },
  CLAIM_PHONE_SAVE: {
    url: '/fsc/claim/ecPhone/saveClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '通讯费报账单保存',
  },
  CLAIM_PHONE_STANDARD: {
    url: '/fsc/base/bc/feeStandard/queryPhoneFeeStd',
    method: 'GET',
    auth: 'zhaoran',
    desc: '通讯费报账明细查询标准',
  },
  CLAIM_PHONE_GETYEARS: {
    url: '/fsc/claim/ecPhone/getYearsAndMonthArr',
    method: 'GET',
    auth: 'zhaoran',
    desc: '通讯费报账明细查询已报销的年月',
  },
  CLAIM_EC_PUB_INVOICE: {
    url: '/fsc/invoice/claimInvoice/getEcInvoicesByClaimId',
    method: 'POST',
    auth: 'zhaoran',
    desc: '发票信息公共页面查询',
  },
  CLAIM_EC_PUB_INVOICE_SAVE: {
    url: '/fsc/invoice/claimInvoice/saveOrUpdateClaimInvoice ',
    method: 'POST',
    auth: 'zhaoran',
    desc: '发票信息初审时保存方法',
  },
  CLAIM_DFAFT_LIST: {
    url: '/fsc/claim/query/drafts/queryResultSetByDto',
    method: 'GET',
    auth: 'zhaoran',
    desc: '报账单草稿箱查询',
  },
  CLAIM_DFAFT_DELETE: {
    url: '/fsc/claim/ecClaim/deleteMultiClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '报账单草稿箱删除',
  },
  CLAIM_DFAFT_INVALID: {
    url: '/fsc/claim/ecClaim/invalidClaim',
    method: 'POST',
    auth: 'zhaoran',
    desc: '报账单草稿箱作废',
  },
  CLAIM_AUDIT_LIST: {
    url: '/fsc/claim/ecClaimApprove/queryClaimListByDto',
    method: 'GET',
    auth: 'zhaoran',
    desc: '报账单待我审批查询',
  },
  CLAIM_MYHANDLE_LIST: {
    url: '/fsc/claim/ecClaimApprove/queryMyHandleClaim',
    method: 'GET',
    auth: 'zhaoran',
    desc: '报账单我审批的查询',
  },
  // 欠付
  EC_ARREAR_DRAFT_LIST: {
    url: '/fsc/arrear/ecArrearApply/getArrearList',
    method: 'GET',
    desc: '欠付草稿箱查询',
    auth: 'zhaoran',
  },
  EC_ARREAR_MYARREAR_LIST: {
    url: '/fsc/arrear/ecArrearApply/getMyArrearList',
    method: 'GET',
    desc: '我的欠付列表',
    auth: 'yuanrr',
  },
  EC_ARREAR_CALLBACK_ARREAR: {
    url: '/fsc/arrear/ecArrearApply/callBackArrear',
    method: 'POST',
    desc: '欠付撤销',
    auth: 'yuanrr',
  },
  EC_ARREAR_AUDIT_LIST: {
    url: '/fsc/arrear/ecArrearApply/queryMyHandleTask',
    method: 'GET',
    desc: '欠付审批查询',
    auth: 'zhaoran',
  },
  EC_ARREAR_AUDIT_DOVIEW: {
    url: '/fsc/arrear/ecArrearApply/doAudit',
    method: 'POST',
    desc: '欠付审批doview',
    auth: 'zhaoran',
  },
  EC_ARREAR_AUDIT_AGREE: {
    url: '/fsc/arrear/ecArrearApply/batchAuditMulti',
    method: 'POST',
    desc: '欠付审批',
    auth: 'zhaoran',
  },
  EC_ARREAR_LIST: {
    url: '/fsc/arrear/ecArrearApply/searchArrearList',
    method: 'GET',
    desc: '欠付列表查询',
    auth: 'zhaoran',
  },
  PJ_QUERY_LIST: {
    url: '/fsc/project/pjProjectApply/queryList',
    method: 'GET',
    auth: 'tt',
    desc: '立项申请',
    mockhandler: 'list',
  },
  PJ_APPLY_LIST: {
    url: '/fsc/project/pjProjectApply/list',
    method: 'GET',
    auth: 'tt',
    desc: '立项申请',
    mockhandler: 'list',
  },

  PJ_TRACK_LIST: {
    url: '/fsc/project/pjProject/queryPjProjectDtoList ',
    method: 'GET',
    auth: 'tt',
    desc: '立项追踪列表',
    mockhandler: 'list',
  },
  PJ_MYDTO_LIST: {
    url: '/fsc/project/pjProjectApply/queryResultSetByDto',
    method: 'GET',
    auth: 'tt',
    desc: '我的立项列表',
    mockhandler: 'list',
  },
  PJ_MYUNDO_LIST: {
    url: '/fsc/project/pjProjectApply/undoTaskRecord',
    method: 'POST',
    auth: 'tt',
    desc: '我的立项撤回',
    mockhandler: 'list',
  },
  PJ_AUDIT_LIST: {
    url: '/fsc/project/pjProjectApply/queryMyHandleTask',
    method: 'GET',
    auth: 'tt',
    desc: '立项审核列表',
    mockhandler: 'list',
  },
  PJ_APPLY_GETONE: {
    url: '/fsc/project/pjProjectApply/getOne',
    method: 'GET',
    auth: 'tt',
    desc: '立项申请',
    mockhandler: 'getone',
  },
  PJ_APPLY_DEL: {
    url: '/fsc/project/pjProjectApply/deleteLogicalById',
    method: 'POST',
    auth: 'tt',
    desc: '立项申请',
    mockhandler: 'delete',
  },
  PJ_APPLY_SAVE: {
    url: '/fsc/project/pjProjectApply/saveOrUpdatePjProject',
    method: 'POST',
    auth: 'tt',
    desc: '立项申请保存',
    mockhandler: 'save',
  },
  PJ_APPLY_AlERT_SAVE: {
    url: '/fsc/project/pjprojectadjust/saveOrUpdatePjProject',
    method: 'POST',
    auth: 'tt',
    desc: '立项申请保存',
    mockhandler: 'save',
  },
  PJ_APPLY_FORMSAVE: {
    url: '/fsc/project/pjProjectApply/addInit',
    method: 'GET',
    auth: 'tt',
    desc: '立项申请',
    mockhandler: 'save',
  },
  PJ_APPLY_DELLALL: {
    url: '/fsc/project/pjProjectApply/deleteMultiByIds',
    method: 'GET',
    auth: 'tt',
    desc: '立项申请批量删除',
    mockhandler: 'save',
  },
  PJ_APPLY_QUERY: {
    url: '/fsc/base/bc/bceckindfield/queryEcKindField',
    method: 'GET',
    auth: 'tt',
    desc: '立项申请',
    mockhandler: 'save',
  },
  QUERY_ECKIND_FIELD: {
    url: '/fsc/base/bc/bceckindfield/queryEcKindFieldByUnitId',
    method: 'GET',
    auth: 'tt',
    desc: '立项申请',
    mockhandler: 'save',
  },
  PJ_APPLY_CLOSE_SAVE: {
    url: '/fsc/project/pjprojectclose/saveOrUpdatePjProject',
    method: 'POST',
    auth: 'tt',
    desc: '立项终止申请',
    mockhandler: 'save',
  },
  PJ_APPLY_CLOSE_SUB: {
    url: '/fsc/project/pjprojectclose/saveAndSubmitPjProject',
    method: 'POST',
    auth: 'tt',
    desc: '立项终止提交保存',
    mockhandler: 'save',
  },
  PJ_APPLY_VOID: {
    url: '/fsc/project/pjProjectApply/invalidRecord',
    method: 'POST',
    auth: 'tt',
    desc: '立项作废',
    mockhandler: 'save',
  },
  PJ_TRACK_VOIDddd: {
    url: '/fsc/project/pjProject/getPjProjectById',
    method: 'GET',
    auth: 'tt',
    desc: '立项追踪详情',
    mockhandler: 'save',
  },
  BC_TRAVEL_STANDARD_QUERY: {
    url: '/fsc/claim/travelstand/selectPageOrderMap',
    method: 'GET',
    auth: 'sj',
    desc: '差旅标准列表',
    mockhandler: 'list',
  },
  BC_TRAVEL_STANDARD_SAVE: {
    url: '/fsc/claim/travelstand/saveOrUpdate',
    method: 'POST',
    auth: 'sj',
    desc: '差旅标标准保存',
    mockhandler: 'saveOrUpdate',
    mocktable: 'saveOrUpdate',
  },
  BC_TRAVEL_STANDARD_GETONE: {
    url: '/fsc/claim/travelstand/getOne',
    method: 'GET',
    auth: 'sj',
    desc: '差旅标标准查询一条记录',
    mockhandler: 'getOne',
    mocktable: 'getOne',
  },
  BC_TRAVEL_STANDARD_DELETE: {
    url: '/fsc/claim/travelstand/deleteMulti',
    method: 'DELETE',
    auth: 'sj',
    desc: '差旅标标准删除',
    mockhandler: 'deleteMulti',
    mocktable: 'deleteMulti',
  },
  BD_TRAVEL_INIT_EC_ITEM: {
    url: '/system/bc/ecItem/getBcEcItems',
    method: 'GET',
    auth: 'sj',
    desc:
      "获取所有的费用项目，然后生成明细。差旅报账参数：entityId=报账公司id,ecKindId=业务类型id,ecLastFlag='1'",
  },
  EC_PUBLIC_PAYABLE_SAVE: {
    url: '/fsc/publicpayment/ecpublicPayementApply/savePublicPaymentApply',
    method: 'POST',
    auth: 'limingxia',
    desc: '预付申请单保存',
  },
  EC_PUBLIC_PAYABLE_FORMSUBMIT: {
    url: '/fsc/publicpayment/ecpublicPayementApply/submitPublicPaymentApply',
    method: 'POST',
    auth: 'limingxia',
    desc: '预付申请单从表单提交数据',
  },
  EC_PUBLIC_PAYABLE_INIT: {
    url: '/fsc/publicpayment/ecpublicPayementApply/addInit',
    method: 'POST',
    auth: 'limingxia',
    desc: '对公预付申请单初始化信息',
  },
  EC_PUBLIC_PAYABLE_DATAINIT: {
    url: '/fsc/publicpayment/ecpublicPayementApply/editRecord',
    method: 'POST',
    auth: 'limingxia',
    desc: '预付申请单详情',
  },
  EC_PUBLIC_PAYSMENT_INIT: {
    url: '/fsc/publicpayment/ecpublicPayementApply/addInit',
    method: 'POST',
    auth: 'tt',
    desc: '对公应付申请单初始化信息',
  },
  EC_PUBLIC_PAYSMENT_SAVE: {
    url: '/fsc/publicpayment/ecpublicPayementApply/savePayablePaymentApply',
    method: 'POST',
    auth: 'tt',
    desc: '对公应付申请单初始化信息暂存',
  },
  EC_PUBLIC_PAYSMENT_FORMSUBMIT: {
    url: '/fsc/publicpayment/ecpublicPayementApply/submitPayablePaymentApply',
    method: 'POST',
    auth: 'tt',
    desc: '对公应付申请单初始化信息提交',
  },
  EC_PUBLIC_PAYSMENT_WITHDCFLAG: {
    url: '/ifs/sap/ifSapVendorPayable/confirmVendorWithDcFlag',
    method: 'POST',
    auth: 'tt',
    desc: '对公应付申请单',
  },
  EC_PUBLIC_PAYSMENT_AUDIT: {
    url: '/fsc/publicpayment/ecpublicPayementApply/submitPayablePaymentApply',
    method: 'POST',
    auth: 'tt',
    desc: '对公应付申请单复核',
  },
  EC_PUBLIC_PAYSMENT_IMPORT: {
    url: '/ifs/sap/ifSapVendorPayable/queryPayableIfDtl',
    method: 'GET',
    auth: 'tt',
    desc: '对公应付申请单导入明细',
  },
  EC_PUBLIC_PAYABLE_SYNC: {
    url: '/ifs/sap/ifSapVendorPayable/syncPayableVendorData',
    method: 'POST',
    auth: 'tt',
    desc: '对公应付导入弹出框的同步按钮',
  },
  CM_APPLY_LIST: {
    url: '/fsc/contract/contractapply/list',
    method: 'GET',
    auth: 'huangh',
    desc: '合同申请列表',
  },
  MD_BANK_ACC_VENDEOR: {
    url: '/system/md/bank/mdBankAccount/getVendorDefaultAccount',
    method: 'POST',
    desc: '供应商带出的默认银行账号',
    auth: 'huangh',
  },
  CM_APPLY_ADDINIT: {
    url: '/fsc/contract/contractapply/addInit',
    method: 'GET',
    auth: 'huangh',
    desc: '合同申请初始化',
  },

  CM_APPLY_GTEONE: {
    url: '/fsc/contract/contractapply/getOne',
    method: 'GET',
    auth: 'huangh',
    desc: '合同申请',
  },

  CM_APPLY_DEL: {
    url: '/fsc/contract/contractapply/batchDelete',
    method: 'POST',
    auth: 'huangh',
    desc: '合同申请删除',
  },
  CM_APPLY_CANCEL: {
    url: '/fsc/contract/contractapply/batchCancel',
    method: 'POST',
    auth: 'huangh',
    desc: '合同申请 作废',
  },

  CM_APPLY_SAVE: {
    url: '/fsc/contract/contractapply/saveOrUpdateCmContract',
    // "url": "/fsc/contract/contractapply/saveOrUpdateCmContract",
    method: 'POST',
    auth: 'huangh',
    desc: '合同申请 保存',
  },
  CM_APPLY_SAVESUB: {
    url: '/fsc/contract/contractapply/saveAndSubmitCmContract',
    method: 'POST',
    auth: 'huangh',
    desc: '合同申请 保存提交',
  },
  CM_APPLY_SUB: {
    url: '/fsc/contract/contractapply/batchSubmitMulti',
    method: 'POST',
    auth: 'huangh',
    desc: '合同申请 提交',
  },
  CM_APPLY_AUDIT: {
    url: '/fsc/contract/contractapply/batchAuditMulti',
    method: 'POST',
    auth: 'huangh',
    desc: '合同申请 审批',
  },
  CM_AUDIT: {
    url: '/fsc/contract/contractapply/batchAudit',
    method: 'POST',
    auth: 'zhaoran',
    desc: '合同的所有审批服务',
  },

  CM_CHANGE_SAVE: {
    url: '/fsc/contract/contractchange/saveOrUpdateCmContract',
    method: 'POST',
    auth: 'huangh',
    desc: '保存',
  },
  CM_CHANGE_SAVESUB: {
    url: '/fsc/contract/contractchange/saveAndSubmitCmContract',
    method: 'POST',
    auth: 'huangh',
    desc: '保存提交',
  },
  CM_CHANGE_SUB: {
    url: '/fsc/contract/contractchange/batchSubmitMulti',
    method: 'POST',
    auth: 'huangh',
    desc: '提交',
  },
  CM_CHANGE_AUDIT: {
    url: '/fsc/contract/contractchange/batchAuditMulti',
    method: 'POST',
    auth: 'huangh',
    desc: '审批',
  },

  CM_CLOSE_SAVE: {
    url: '/fsc/contract/contractclose/saveOrUpdateCmContract',
    method: 'POST',
    auth: 'huangh',
    desc: '保存',
  },
  CM_CLOSE_SAVESUB: {
    url: '/fsc/contract/contractclose/saveAndSubmitCmContract',
    method: 'POST',
    auth: 'huangh',
    desc: '保存提交',
  },
  CM_CLOSE_SUB: {
    url: '/fsc/contract/contractclose/batchSubmitMulti',
    method: 'POST',
    auth: 'huangh',
    desc: '提交',
  },
  CM_CLOSE_AUDIT: {
    url: '/fsc/contract/contractclose/batchAuditMulti',
    method: 'POST',
    auth: 'huangh',
    desc: '审批',
  },

  CLAIM_EC_DIRECT_ADD: {
    url: '/fsc/claim/ecPublicDirect/addInit',
    method: 'POST',
    auth: 'huangh',
    desc: '对公通用报账 add',
  },
  CLAIM_EC_DIRECT_SAVE: {
    url: '/fsc/claim/ecPublicDirect/saveClaim',
    method: 'POST',
    auth: 'huangh',
    desc: '对公通用报账 save',
  },
  CLAIM_EC_DIRECT_SUB: {
    url: '/fsc/claim/ecPublicDirect/submitClaim',
    method: 'POST',
    auth: 'huangh',
    desc: '对公通用报账 提交',
  },
  EC_DIRECT_EDITRECORD: {
    url: '/fsc/claim/ecPublicDirect/editRecord',
    method: 'POST',
    auth: 'huangh',
    desc: '对公通用报账 查询数据',
  },

  CLAIM_EC_PUB_PAYMENT: {
    url: '/fsc/claim/ecClaimPayment/queryClaimPaymentList',
    method: 'POST',
    auth: 'huangh',
    desc: '报账单 支付信息 ',
  },

  CLAIM_EC_PUB_PAYMENT_FIRSTCHECK: {
    url: '/fsc/claim/ecClaimPayment/updateClaimPayment',
    method: 'POST',
    auth: 'huangh',
    desc: '报账单 支付信息 初审保存firstCheck',
  },

  CLAIM_EC_PUB_ADVPAYRESULT: {
    url: '/fsc/claim/fiAdvPay/selectFiAdvPayResult',
    method: 'GET',
    auth: 'huangh',
    desc: '报账单 对公核销 ',
  },
  CLAIM_FI_PSN_LOAN_OFFSET_LIST: {
    url: '/fsc/claim/fiPsnLoan/selectFiPsnLoanOffSetResult',
    method: 'GET',
    auth: 'xia_zhh',
    desc: '报账单 对私核销编辑查询 ',
  },
  CLAIM_EC_PSN_LOAN_OFFSET_LIST: {
    url: '/fsc/claim/ecPsnLoanOffset/selectEcPsnLoanOffsetResult',
    method: 'GET',
    auth: 'xia_zhh',
    desc: '报账单 对私核销查看查询 ',
  },

  BD_FORECAST_EXPENSE_LIST: {
    url: '/fsc/budget/forecastExpense/list',
    method: 'GET',
    auth: 'xiazhonghua',
    desc: '月度变动费用列表',
  },
  BD_FORECAST_EXPENSE_GETONE: {
    url: '/fsc/budget/forecastExpense/getOne',
    method: 'GET',
    auth: 'xiazhonghua',
    desc: '月度变动费用详情查询',
  },
  BD_FORECAST_EXPENSE_SAVE: {
    url: '/fsc/budget/forecastExpense/saveOrUpdate',
    method: 'POST',
    auth: 'xiazhonghua',
    desc: '月度变动费用详情保存',
  },
  BD_FORECAST_EXPENSE_DEL: {
    url: '/fsc/budget/forecastExpense/deleteByDto',
    method: 'POST',
    auth: 'xiazhonghua',
    desc: '月度变动费用删除',
  },
  BD_FORECAST_EXPENSE_SUBMIT: {
    url: '/fsc/budget/forecastExpense/submitByDto',
    method: 'POST',
    auth: 'xiazhonghua',
    desc: '月度变动费用提交',
  },
  BD_FORECAST_EXPENSE_BACK: {
    url: '/fsc/budget/forecastExpense/backByDto',
    method: 'POST',
    auth: 'xiazhonghua',
    desc: '月度变动费用退回',
  },
  BD_FORECAST_EXPENSE_COMPLETE: {
    url: '/fsc/budget/forecastExpense/completeByDto',
    method: 'POST',
    auth: 'xiazhonghua',
    desc: '月度变动费用同意',
  },
  BD_FORECAST_EXPENSE_EFFECT: {
    url: '/fsc/budget/forecastExpense/effectByDto',
    method: 'POST',
    auth: 'xiazhonghua',
    desc: '月度变动费用生效',
  },

  PJ_ALERT_AUDIT: {
    url: '/fsc/project/pjProjectApply/batchAudit',
    method: 'POST',
    auth: 'huangh',
    desc: '立项总审批服务zhaoran',
  },
  PJ_CLOSE_AUDIT: {
    url: '/fsc/project/pjprojectclose/batchAuditMulti',
    method: 'POST',
    auth: 'huangh',
    desc: '事项申请 审批',
  },
  PJ_APPLY_DELS: {
    url: '/fsc/project/pjProjectApply/deleteMultiByIds',
    method: 'POST',
    auth: 'huangh',
    desc: '立项申请批量删除',
  },
  PJ_APPLY_SUB: {
    url: '/fsc/project/pjProjectApply/saveAndSubmitPjProject',
    method: 'POST',
    auth: 'huangh',
    desc: '立项申请 提交',
  },
  PJ_APPLY_AlERT_SUB: {
    url: '/fsc/project/pjprojectadjust/saveAndSubmitPjProject',
    method: 'POST',
    auth: 'huangh',
    desc: '立项变更 提交',
  },

  PJ_APPLY_AlERT_DETAIL: {
    url: '/fsc/project/pjProject/getPjProjectById',
    method: 'GET',
    auth: 'tt',
    desc: '立项变更 点击lookup后带出明细信息',
  },
  PJ_AUDIT: {
    url: '/fsc/project/pjProjectApply/batchAudit',
    method: 'POST',
    auth: 'tt',
    desc: '立项审批单条',
  },
  ADD_ARREAR_APPLY: {
    url: '/fsc/arrear/ecArrearApply/addArrearApply',
    method: 'GET',
    auth: 'xs',
    desc: '分摊',
    mockhandler: 'list',
  },
  ECARREARDTL_GETONE: {
    url: '/fsc/arrear/ecArrearDtl/getEcArrearDtlById',
    method: 'GET',
    auth: 'xs',
    desc: '分摊明细',
    mockhandler: 'list',
  },
  ECARREAR_SUBMIT: {
    url: '/fsc/arrear/ecArrearApply/submitArrearApply',
    method: 'POST',
    auth: 'yangh',
    desc: '欠付提交',
  },
  ECALCA_GET: {
    url: '/fsc/alca/ecAlcaApply/queryEcAlca',
    method: 'GET',
    auth: 'yangh',
    desc: '欠付分摊',
    mockhandler: 'list',
  },
  ECALCA_SAVE: {
    url: '/fsc/alca/ecAlcaApply/saveAlcaApply',
    method: 'POST',
    auth: 'yangh',
    desc: '欠付分摊保存',
    mockhandler: 'list',
  },
  ECALCADTL_GET: {
    url: '/fsc/alca/ecAlcaApply/queryEcAlcaDtlByAlcaId',
    method: 'GET',
    auth: 'xs',
    desc: '欠付分摊',
    mockhandler: 'list',
  },
  ECARREAR_GET: {
    url: '/fsc/arrear/ecArrearApply/queryEcArrearByIds',
    method: 'GET',
    auth: 'xs',
    desc: '分摊',
    mockhandler: 'list',
  },

  ASSET_APPLY_DEL: {
    url: '/fsc/claim/ecAssetApply/deleteOneLogic',
    method: 'DELETE',
    desc: '资产卡片申请 删除',
    auth: 'huangh',
  },
  ASSET_APPLY_GETONE: {
    url: '/fsc/claim/ecAssetApply/editRecord',
    method: 'POST',
    desc: '资产卡片申请 修改',
    auth: 'huangh',
  },
  ASSET_APPLY: {
    url: '/fsc/claim/ecAssetApply/queryAsset',
    method: 'GET',
    desc: '资产卡片 申请查询',
    auth: 'huangh',
  },
  ASSET_APPLY_SAVE: {
    url: '/fsc/claim/ecAssetApply/saveAsset',
    method: 'POST',
    desc: '资产卡片  申请 保存 ',
    auth: 'huangh',
  },
  EC_ASSET_APPLY_ADDINIT: {
    url: '/fsc/claim/ecAssetApply/initAsset',
    method: 'GET',
    desc: '资产卡片 申请 新增初始化',
    auth: 'huangh',
  },
  EC_ASSET_ADDINIT: {
    url: '/fsc/ecpublic/ecpublicapply/addInit',
    method: 'GET',
    desc: '资产卡片 新增初始化',
    auth: 'huangh',
  },
  EC_ASSET_SAVE: {
    url: '/fsc/ecpublic/ecpublicapply/saveEcPublicApply',
    method: 'POST',
    desc: '资产卡片 暂存',
    auth: 'huangh',
  },
  EC_ASSET_SAVE_SUB: {
    url: '/fsc/ecpublic/ecpublicapply/submitClaim',
    method: 'POST',
    desc: '资产卡片 提交',
    auth: 'huangh',
  },
  EC_ASSET_GETONE: {
    url: '/fsc/ecpublic/ecpublicapply/editRecord',
    method: 'POST',
    desc: '资产卡片 提交',
    auth: 'huangh',
  },

  EC_ECAR_ADDINIT: {
    url: '/fsc/claim/ecArClaimQf/addInit',
    method: 'POST',
    desc: '对公欠付 新增初始化',
    auth: 'huangh',
  },
  EC_ECAR_SAVE: {
    url: '/fsc/claim/ecArClaimQf/saveOrUpdateEcArClaim',
    method: 'POST',
    desc: '对公欠付 编辑页面保存或者更新',
    auth: 'huangh',
  },
  EC_ECAR_SAVE_SUB: {
    url: '/fsc/claim/ecArClaimQf/submitRecord',
    method: 'POST',
    desc: '对公欠付 提交',
    auth: 'huangh',
  },
  EC_ECAR_EDITRECORD: {
    url: '/fsc/claim/ecArClaimQf/editRecord',
    method: 'POST',
    desc: '对公欠付 ',
    auth: 'huangh',
  },

  CM_CHANGE_BYID: {
    url: '/fsc/contract/contractquery/getCmContractDtoById',
    method: 'GET',
    auth: 'huangh',
    desc: '变更明细',
  },
  CM_APPLY_PROJECT: {
    url: '/fsc/project/pjProject/getPjBudgetCtrlForLookUp',
    method: 'GET',
    auth: 'huangh',
    desc: 'bd明细 新增 ',
    param: 'projectId=146',
  },
  EC_ALCA_OFFSET_LIST: {
    url: '/fsc/claim/ecAlcaOffset/selectEcAlcaAndOffsetDtoResult',
    method: 'POST',
    auth: 'tt',
    desc: '待摊核销',
  },
  FSC_VOUCHER_APPLY_DELET: {
    url: '/ve/fivoucher/fiVoucherHeader/deletePatch',
    method: 'DELETE',
    desc: '非费用类总账批量删除',
    auth: 'lichunxiao',
  },
  FSC_VOUCHER_APPLY_INVALID: {
    url: '/ve/fivoucher/fiVoucherHeader/cancleVoucher',
    method: 'POST',
    desc: '非费用类总账 作废',
    auth: 'lichunxiao',
  },
  FSC_VOUCHER_APPLY_INIT: {
    url: '/ve/fivoucher/fiVoucherHeader/selectByParam',
    method: 'POST',
    desc: '非费用类总账列表',
    auth: 'lichunxiao',
  },
  FSC_VOUCHER_APPLY_DETAIL: {
    url: '/ve/fivoucher/fiVoucherHeader/addOrEdit',
    method: 'POST',
    desc: '非费用类总账行情',
    auth: 'lichunxiao',
  },
  FSC_VOUCHER_APPLY_SUBMIT: {
    url: '/ve/fivoucher/fiVoucherHeader/submitCheck',
    method: 'POST',
    desc: '非费用类总账 提交',
    auth: 'lichunxiao',
  },
  FSC_VOUCHER_APPLY_SAVE: {
    url: '/ve/fivoucher/fiVoucherHeader/saveOrUpdateVoucher',
    method: 'POST',
    desc: '非费用类总账 暂存',
    auth: 'lichunxiao',
  },
  FSC_VOUCHER_APPLY_REVIEW: {
    url: '/ve/fivoucher/fiVoucherHeader/submitVoucher',
    method: 'POST',
    desc: '非费用类总账 复核',
    auth: 'lichunxiao',
  },
  FSC_VOUCHER_APPLY_BATCHREVIEW: {
    url: '/ve/fivoucher/fiVoucherHeader/submitVoucherPatch',
    method: 'POST',
    desc: '非费用类总账 批量复核',
    auth: 'lichunxiao',
  },
  FSC_FI_APPLY_INIT: {
    url: '/fsc/claim/ecpublic/voucher/addInit',
    method: 'POST',
    desc: '费用类总账',
    auth: 'lichunxiao',
  },
  FSC_FI_APPLY_SAVE: {
    url: '/fsc/claim/ecpublic/voucher/saveRecord',
    method: 'POST',
    desc: '费用类总账 保存',
    auth: 'lichunxiao',
  },
  FSC_FI_APPLY_SUBMIT: {
    url: '/fsc/claim/ecpublic/voucher/submitRecord',
    method: 'POST',
    desc: '费用类总账 提交',
    auth: 'lichunxiao',
  },
  FSC_EC_TRAVEL_LIST: {
    url: '/fsc/claim/ectravel/editRecord',
    method: 'get',
    mockhandler: 'list',
    mocktable: 'EC_TRAVEL',
    desc: '差旅报账单修改初始化',
    auth: 'wennn',
  },
  FSC_EC_TRAVEL_EDIT_RECORD: {
    url: '/fsc/claim/ectravel/editRecord',
    method: 'post',
    mockhandler: 'getone',
    mocktable: 'EC_TRAVEL',
    desc: '差旅报账单修改初始化',
    auth: 'wennn',
  },
  FSC_EC_TRAVEL_VIEW_RECORD: {
    url: '/fsc/claim/ectravel/viewRecord',
    method: 'post',
    desc: '差旅报账单查看',
    auth: 'wennn',
  },
  FSC_EC_TRAVEL_EDIT_INIT: {
    url: '/fsc/claim/ectravel/addInit',
    method: 'post',
    desc: '差旅报账单新增初始化',
    auth: 'wennn',
  },
  FSC_EC_TRAVEL_SAVE_OR_UPDATE: {
    url: '/fsc/claim/ectravel/saveClaim',
    method: 'post',
    desc: '差旅报账单报账或者修改',
    auth: 'wennn',
  },
  FSC_BC_EXCHANGE_RATE_QUERY: {
    url: '/fsc/base/bc/bcExchangeRate/queryExchangeRate',
    method: 'post',
    desc: '初始化汇率获取服务,currencyId原币币种id,rateType:M汇率类型,targetCurrencyId,目标币种id',
    auth: 'wennn',
  },
  FSC_EC_TRAVEL_SUBMIT_RECORD: {
    url: '/fsc/claim/ectravel/submitClaim',
    method: 'post',
    desc: '差旅报账单提交',
    auth: 'wennn',
  },
  FSC_EC_TRAVEL_QUERY_FEESTD: {
    url: '/fsc/base/bc/feeStandard/queryTravelFeesStd',
    method: 'get',
    desc: '根据费用项目获取差-获取差旅标',
    auth: 'wennn',
  },
  FSC_EC_TRAVEL_QUERY_STDEXRATE: {
    url: '/fsc/base/bc/feeStandard/queryStdExRate',
    method: 'get',
    desc: '根据原币币种切换仅获取汇率-获取标准币种汇率',
    auth: 'wennn',
  },
  FSC_EC_PPCAR_SAVECLAIM: {
    url: '/fsc/claim/ecppcar/saveClaim',
    method: 'post',
    auth: 'yuanrr',
    desc: '私车公用保存',
  },
  FSC_EC_PPCAR_EDITRECORD: {
    url: '/fsc/claim/ecppcar/editRecord',
    method: 'post',
    auth: 'yuanrr',
    desc: '私车公用修改',
  },
  FSC_EC_PPCAR_SUBMITCLAIM: {
    url: '/fsc/claim/ecppcar/submitClaim',
    method: 'post',
    auth: 'yuanrr',
    desc: '私车公用提交',
  },
  FSC_EC_PPCAR_VIEWRECORD: {
    url: '/fsc/claim/ecppcar/viewRecord',
    method: 'post',
    auth: 'yuanrr',
    desc: '私车公用查看',
  },
  FSC_EC_PPCAR_QUERY_FEESTD: {
    url: '/fsc/base/bc/feeStandard/queryVehicleFeeStd',
    method: 'get',
    desc: '获取私车公用标准',
    auth: 'yuanrr',
  },
  FSC_EC_PPCAR_GETMILEAGES: {
    url: '/fsc/claim/ecdaily/getMileages',
    method: 'get',
    desc: '获取报账人已报销里程数',
    auth: 'yuanrr',
  },

  FSC_EC_ARCLAIM_EDITRECORD: {
    url: '/fsc/claim/ecArClaimYt/editRecord',
    method: 'post',
    auth: 'yuanrr',
    desc: '预提待摊页面初始化',
  },
  CLAIM_EC_ARREAR_ADD: {
    url: '/fsc/arrear/ecArrearApply/addInit',
    method: 'GET',
    desc: '统计性欠付初始化',
    auth: 'yangh',
  },
  CLAIM_EC_ARREAR_SAVE: {
    url: '/fsc/arrear/ecArrearApply/saveArrearApply',
    method: 'POST',
    desc: '统计性欠付暂存',
    auth: 'yangh',
  },
  CLAIM_EC_ARREAR_SUB: {
    url: '/fsc/arrear/ecArrearApply/submitArrearApplyStatistics',
    method: 'POST',
    desc: '统计性欠付提交',
    auth: 'yangh',
  },
  CLAIM_EC_ARREAR_GETONE: {
    url: '/fsc/arrear/ecArrearApply/queryEcArrearByIds',
    method: 'GET',
    desc: '统计性欠付修改',
    auth: 'yangh',
  },

  EC_AR_CLAIM_LIST: {
    url: '/fsc/claim/ecArClaimYt/list',
    method: 'GET',
    desc: '欠付预提列表',
    auth: 'yangh',
  },
  EC_AR_CLAIM_GTEONE: {
    url: '/fsc/claim/ecArClaimYt/getOne',
    method: 'GET',
    desc: '欠付预提编辑查看',
    auth: 'yangh',
  },
  EC_AR_CLAIM_VIEW_ARREAR_ALCA: {
    url: '/fsc/alca/arrearalca/queryViewArrearAlcaDialog',
    method: 'GET',
    desc: '欠付预提新增选择',
    auth: 'yangh',
  },
  EC_AR_CLAIM_CREATE: {
    url: '/fsc/claim/ecArClaimYt/saveYtEcArClaim',
    method: 'POST',
    desc: '欠付预提新增生成',
    auth: 'yangh',
  },
  EC_AR_CLAIM_SAVE: {
    url: '/fsc/claim/ecArClaimYt/saveOrUpdateEcArClaim',
    method: 'POST',
    desc: '欠付预提暂存',
    auth: 'yangh',
  },
  EC_AR_CLAIM_SUB: {
    url: '/fsc/claim/ecArClaimYt/submitRecord',
    method: 'POST',
    desc: '欠付预提提交',
    auth: 'yangh',
  },
  EC_AR_CLAIM_DEL: {
    url: '/fsc/claim/ecArClaimYt/deleteLogicalByIds',
    method: 'POST',
    desc: '欠付预提删除',
    auth: 'yangh',
  },
  SEARCH_LINK: {
    url: '/system/rc/rcFlowHandleUrl/findRecord',
    method: 'POST',
    desc: '查询链接',
    auth: 'tt',
  },
  // VOUCHER_LIST: {
  //     "url": "/ve/vgdocvoucher/VoucherTemplete/voucherGenerator",
  //     "method": "GET",
  //     "auth": "linzm",
  //     "desc": "凭证信息",
  // },
  VOUCHER_LIST: {
    url: '/ve/vgdocvoucher/VoucherTemplete/queryVouchers',
    method: 'GET',
    auth: 'linzm',
    desc: '凭证信息',
  },
  FSC_FINANCE_FIRSTAUDIT_PASS: {
    url: '/fsc/finance/fiValidateAudit/firstAuditPass',
    method: 'POST',
    auth: 'why',
    desc: '初审通过',
  },
  FSC_FINANCE_FIRSTAUDIT_BACK: {
    url: '/fsc/finance/fiValidateAudit/rollbackRecord',
    method: 'POST',
    auth: 'why',
    desc: '初审退回',
  },
  FSC_FINANCE_FIRSTAUDIT_COMMUNICATE: {
    url: '/fsc/finance/fiValidateAudit/firstAuditCommunicate',
    method: 'POST',
    auth: 'why',
    desc: '初审沟通',
  },
  FSC_FINANCE_RECHECK_PASS: {
    url: '/fsc/finance/fiReCheckAudit/checkAuditPass',
    method: 'POST',
    auth: 'why',
    desc: '复核通过',
  },
  FSC_FINANCE_RECHECK_COMMUNICATE: {
    url: '/fsc/finance/fiReCheckAudit/checkAuditCommunicate',
    method: 'POST',
    auth: 'why',
    desc: '复核沟通',
  },
  FSC_FINANCE_RECHECK_CLAIMBOOK: {
    url: '/fsc/finance/fiReCheckAudit/autoClaimBook',
    method: 'POST',
    auth: 'why',
    desc: '在线记账',
  },
  FSC_FINANCE_RECHECK_BOOKCOMPLETE: {
    url: '/fsc/finance/fiReCheckAudit/doConfirmBookComplete',
    method: 'POST',
    auth: 'why',
    desc: '确认记账完成',
  },
  FSC_FINANCE_RECHECK_BACK: {
    url: '/fsc/finance/fiReCheckAudit/backRecord',
    method: 'POST',
    auth: 'why',
    desc: '复核退回',
  },
  FSC_FINANCE_RECHECK_SAVE_CALCA: {
    url: '/fsc/claim/ecAlcaOffset/saveOrUpdateEcAlcaAndOffset',
    method: 'POST',
    auth: 'hxl',
    desc: '待摊核销的保存',
  },
  FSC_FINANCE_REDFLUSH_LIST: {
    url: '/fsc/finance/ecWriteoff/queryResultSetByDtoForWriteOff',
    method: 'get',
    auth: 'yuanrr',
    desc: '初始化新增红冲获取数据',
  },
  FSC_FINANCE_REDFLUSH_DELETEMULTI: {
    url: '/fsc/finance/ecWriteoff/deleteMultiClaim',
    method: 'POST',
    auth: 'yuanrr',
    desc: '删除',
  },
  FSC_FINANCE_REDFLUSH_GETONE: {
    url: '/fsc/finance/ecWriteoff/getOne',
    method: 'get',
    auth: 'yuanrr',
    desc: '单条红冲数据获取',
  },
  FSC_FINANCE_REDFLUSH_LISTBYDTO: {
    url: '/fsc/finance/ecWriteoff/listByDto',
    method: 'get',
    auth: 'yuanrr',
    desc: '财务红冲列表',
  },
  FSC_FINANCE_REDFLUSH_SVAE: {
    url: '/fsc/finance/ecWriteoff/saveWriteoff',
    method: 'POST',
    auth: 'yuanrr',
    desc: '保存',
  },
  FSC_FINANCE_REDFLUSH_DOCONVERT: {
    url: '/fsc/finance/ecWriteoff/doConvertWriteOff',
    method: 'POST',
    auth: 'yuanrr',
    desc: '创建红冲',
  },
  FSC_FINANCE_REDFLUSH_SUBMIT: {
    url: '/fsc/finance/ecWriteoff/submitWriteOff',
    method: 'POST',
    auth: 'yuanrr',
    desc: '提交',
  },
  FSC_FINANCE_REDFLUSH_PASS: {
    url: '/fsc/finance/ecWriteoff/checkAuditPass',
    method: 'POST',
    auth: 'yuanrr',
    desc: '红冲审批通过',
  },
  FSC_FINANCE_REDFLUSH_BACK: {
    url: '/fsc/finance/ecWriteoff/backRecord',
    method: 'POST',
    auth: 'yuanrr',
    desc: '红冲审批退回',
  },
  FSC_SIGN_ENTITY: {
    url: '/system/md/mdEntity/searchMdEntityTreeList',
    method: 'POST',
    auth: 'linzm',
    desc: '加签_查询组织机构树',
  },
  FSC_SIGN_ENTITYSTAFF: {
    url: '/system/lookup/selectUserInfoForLookup',
    method: 'GET',
    auth: 'linzm',
    desc: '加签_查询组织下人员',
  },
  FSC_VOUCHER_APPLY_REVIEWLIST: {
    url: '/ve/fivoucher/fiVoucherHeader/checkVoucherList',
    method: 'POST',
    desc: '复核  列表 ',
    auth: 'lichunxiao',
  },
  FSC_VOUCHER_APPLY_ABCKREVIEW: {
    url: '/ve/fivoucher/fiVoucherHeader/backVoucher',
    method: 'POST',
    desc: '复核列表 退回',
    auth: 'lichunxiao',
  },
  RC_FLOW_PROPERTYLIST: {
    url: '/system/rc/rcFlowActivityProperty/queryWorkFlowAuth',
    method: 'GET',
    desc: '授权人查询列表',
    auth: 'lichunxiao',
  },
  RC_FLOW_PROPERTY_DELET: {
    url: '/system/rc/rcFlowActivityProperty/deleteWorkFlowAuthProp',
    method: 'POST',
    desc: '授权人删除',
    auth: 'lichunxiao',
  },
  RC_FLOW_PROPERTY_SAVE: {
    url: '/system/rc/rcFlowActivityProperty/saveWorkFlowAuthProp',
    method: 'POST',
    desc: '授权人保存',
    auth: 'lichunxiao',
  },
  RC_FLOW_PROPERTY_EDIT: {
    url: '/system/rc/rcFlowActivityProperty/getWorkFlowAuth',
    method: 'POST',
    desc: '授权人编辑',
    auth: 'lichunxiao',
  },
  FSC_FI_APPLY_EDIT: {
    url: '/fsc/claim/ecpublic/voucher/editRecord',
    method: 'POST',
    desc: '费用类总账修改',
    auth: 'lichunxiao',
  },
  FSC_FI_APPLY_RATE: {
    url: '',
    method: 'POST',
    desc: '费用类总账 汇率',
    auth: 'lichunxiao',
  },
  FSC_FI_APPLY_INVALID: {
    url: '/fsc/arrear/ecArrearApply/invalidArrear',
    method: 'POST',
    desc: '我的欠付单作废',
    auth: 'hxl',
  },
  FSC_FI_APPLY_DELETE: {
    url: '/fsc/arrear/ecArrearApply/deleteMultiArrear',
    method: 'POST',
    desc: '我的欠付单删除',
    auth: 'hxl',
  },
  FSC_FI_REVIEWAPPLY_INIT: {
    url: '/fsc/claim/ecpublic/voucher/viewRecord',
    method: 'POST',
    desc: '查看 费用类总账',
    auth: 'lichunxiao',
  },
  FSC_BUDGET_CTRL_FOR_BCECITEM: {
    url: '/fsc/budget/budgetCtrl/queryBudgetCtrlListForBcEcItem',
    method: 'GET',
    desc: '查询费用项目对应的预算控制数据',
    auth: 'xia_zhh',
  },
  FSC_BUDGET_OCLIST_FOR_BCECITEM: {
    url: '/fsc/budget/preCtrl/queryOcList',
    method: 'GET',
    desc: '查询费用项目对应的占用记录',
    auth: 'xia_zhh',
  },
  MYCLAIM_LIST: {
    url: '/fsc/claim/query/myclaim/queryResultSetByDto',
    method: 'GET',
    desc: '我报销的--查询',
    auth: 'linzm',
  },
  CONFIRM_WRITEOFF: {
    url: '/fsc/finance/ecWriteoff/doConfirmWriteoff',
    method: 'POST',
    desc: '预提待摊确认红冲结果',
    auth: 'yuanrr',
  },
  CONFIRM_WRITEOFFBATCH: {
    url: '/fsc/finance/ecWriteoff/doConfirmWriteoffBatch',
    method: 'POST',
    desc: '批量预提待摊确认红冲结果',
    auth: 'yuanrr',
  },
  FSC_EC_ARCLAIM_INVALID: {
    url: '/fsc/claim/ecArClaimYt/invalidClaim',
    method: 'POST',
    desc: '预提待摊作废',
    auth: 'yangh',
  },
  FSC_CLAIM_EC_BACKCLAIM: {
    url: '/fsc/claim/ecClaim/callBackClaim',
    method: 'POST',
    desc: '我报销的 撤回',
    auth: 'huangh',
  },
  FSC_PJ_HISTORYTRACK: {
    url: '/fsc/project/pjProject/queryHistoricalTracing',
    method: 'GET',
    desc: '立项追踪 历史追踪',
    auth: 'hanxiaoling',
  },
  FSC_PJ_ARREAR_DTL: {
    url: '/fsc/project/pjProject/queryArrearExecutionTracking',
    method: 'GET',
    desc: '立项追踪 执行追踪 欠付明细',
    auth: 'hanxiaoling',
  },
  FSC_PJ_REIM_DTL: {
    url: '/fsc/project/pjProject/queryClaimExecutionTracking',
    method: 'GET',
    desc: '立项追踪 执行追踪 报账明细',
    auth: 'hanxiaoling',
  },
  TRAVEL_STANDARD_LIST: {
    url: '/fsc/base/bc/feeStandard/queryListByPage',
    method: 'GET',
    auth: 'zhaoran',
    desc: '差旅标准列表查询',
  },
  TRAVEL_STANDARD_GETONE: {
    url: '/fsc/base/bc/feeStandard/getOne',
    method: 'GET',
    auth: 'zhaoran',
    desc: '差旅标准详情',
  },
  TRAVEL_STANDARD_SAVE: {
    url: '/fsc/base/bc/feeStandard/saveOrUpdate',
    method: 'POST',
    auth: 'zhaoran',
    desc: '差旅标准保存',
  },
};
