export default {
    USER_LIST: {
        "url": "/system/lookup/selectUserInfoForLookup",
        "method": "GET",
        "desc": "员人(报账人)",
        "auth": "huangh",
    },
    USER_TRAVEL_LIST: {
        "url": "/system/lookup/searchUserInfoCommonForLookup",
        "method": "GET",
        "desc": "员人(差旅报账人)",
        "auth": "wennn",
    },
    USER_EXT_LIST: {
        "url": "/system/lookup/serachUserInfoExtForLookup",
        "method": "GET",
        "desc": "员人(报账人扩展信息)",
        "auth": "huangh",
    },
    EC_ARREAR_DTL: {
        "url": "/fsc/arrear/ecArrearDtl/selectEcArrearDtlAll",
        "method": "GET",
        "desc": "对公欠付报账单---报账明细 新增弹窗",
        "auth": "huangh",
    },
    EC_ASSET_DTL: {
        "url": "/fsc/claim/ecAssetApply/searchEcClaimAssetForLookup",
        "method": "GET",
        "desc": "资产报账单---报账明细 新增弹窗",
        "auth": "huangh",
    },
    REIM_UNIT_LIST: {
        "url": "/system/lookup/getUnitSelect",
        "method": "GET",
        "desc": "报账公司",
        "auth": "huangh",
    },
    SELECT_ROLE_INFO: {
        "url": "/system/lookup/serachRoleInfoForLookup",
        "method": "GET",
        "desc": "角色",
        "auth": "huangh",
    },
    SELECT_POS_LEVEL: {
        "url": "/system/bc/bcPositionLevel/queryBcPositionLevelForLookUp",
        "method": "GET",
        "desc": "角色",
        "auth": "huangh",
    },
    REIM_OTHERS_UNIT_LIST: {
        "url": "/system/lookup/searchRespUnitForLookup",
        "method": "GET",
        "desc": "他方承担其他公司",
        "auth": "tt",
    },
    REIM_ENTITY_LIST: {
        "url": "/system/lookup/getOrgEntitySelect",
        "method": "GET",
        "desc": "报账部门",
        "auth": "huangh",
    },
    REIM_ENTITY: {
        "url": "/system/lookup/getOrgEntitySelectForReim",
        "method": "GET",
        "desc": "报账部门(加权限）",
        "auth": "linzm",
    },
    BD_UNIT_LIST: {
        "url": "/system/lookup/searchBdEntityForLookup",
        "method": "GET",
        "desc": "预算单元，预算体",
        "auth": "huangh",
    },
    BUDGET_YEAR_LIST: {
        "url": "/system/lookup/searchPeriodForLookup",
        "method": "GET",
        "desc": "预算年度",
        "auth": "xiazhonghua",
    },
    BD_USER_UNIT_LIST: {
        "url": "/system/lookup/searchBdEntityForLookup",
        "method": "GET",
        "desc": "根据当前登录人查询有权限的预算单元，预算体传2",
        "auth": "huangh",
    },
    BD_POWER_UNIT_LIST: {
        "url": "/system/lookup/searchBdEntityForLookupForPrivilege",
        "method": "GET",
        "desc": "预算承担部门 有权限",
        "auth": "tt",
    },
    MD_CORP_LIST: {
        "url": "/system/lookup/getMdCorpForLookupSelect",
        "method": "GET",
        "desc": "结算单位",
        "auth": "huangh",
    },
    FI_BOOK_LIST: {
        "url": "/system/lookup/queryBcFiBookLookup",
        "method": "GET",
        "desc": "公司代码(记账公司)",
        "auth": "huangh",
    },
    FI_ENTITY_LIST: {
        "url": "/system/lookup/queryBcFiEntityLookup",
        "method": "GET",
        "desc": "成本中心",
        "auth": "huangh",
    },
    FI_PROFIT_CENTER_LIST: {
        "url": "/system/lookup/queryProfitCenter",
        "method": "GET",
        "desc": "利润中心",
        "auth": "huangh",
    },
    BC_DOC_KIND_LIST: {
        "url": "/system/lookup/getBcDocKindsForLookup",
        "method": "GET",
        "desc": "单据类型",
        "auth": "huangh",
    },
    BC_ECITEM_LIST: {
        "url": "/system/lookup/getBcEcItemsForLookup",
        "method": "GET",
        "desc": "报账项目（费用项目）",
        "auth": "huangh",
    },
    BD_ITEM_LIST: {
        "url": "/system/lookup/getBdItemsForLookup",
        "method": "GET",
        "desc": "预算项目",
        "auth": "xia_zhh",
    },
    BUSINESS_TYPE_LIST: {
        "url": "/system/lookup/getBcEcKindsForLookup",
        "method": "GET",
        "desc": "业务类型",
        "auth": "huangh",
    },
    MD_CURRENCY_LIST: {
        "url": "/system/lookup/getMdCurrencyForLookupSelect",
        "method": "GET",
        "desc": "币种",
        "auth": "huangh",
    },
    MD_BANK_ACCOUNT_LIST: {
        "url": "/system/lookup/getMdBankAccountForLookup",
        "method": "GET",
        "desc": "银行账号",
        "auth": "huangh",
    },
    MD_PARTNER_LIST: {
        "url": "/system/lookup/getMdPartnerForLookUp",
        "method": "GET",
        "desc": "供应商(业务伙伴)",
        "auth": "huangh",
    },
    MD_PAYABLE_PARTER_LIST: {
        "url": "/system/lookup/getMdPartnerForLookUpForPrivilege",
        "method": "GET",
        "desc": "供应商(带权限)",
        "auth": "tt",
    },
    MD_PAYMENT_LIST: {
        "url": "/system/lookup/getMdPaymentModes",
        "method": "GET",
        "desc": "结算方式(付款方式)",
        "auth": "linzm",
    },
    MD_DISTRICT_COUNTRY_LIST: {
        "url": "/system/lookup/queryCountryListForLookUp",
        "method": "GET",
        "desc": "国家",
        "auth": "zhaor",
    },
    MD_DISTRICT_CLASSIFY_LIST: {
        "url": "/system/lookup/getMdDistrictClassifyForLookup",
        "method": "GET",
        "desc": "地区分类",
        "auth": "linzm",
    },
    MD_DISTRICT_CITY_LIST: {
        "url": "/system/lookup/queryDistrictListForLookUp",
        "method": "GET",
        "desc": "城市",
        "auth": "linzm",
    },
    MD_TRAVEL_DISTRICT_CITY_LIST: {
        "url": "/system/lookup/queryDistrictWithClassifyForLookUp",
        "method": "GET",
        "desc": "城市",
        "auth": "wennn",
    },
    MD_TRAVEL_DISTRICT_CLASSIFY: {
        "url": "/system/md/mdDistrict/queryDistrictClassify",
        "method": "GET",
        "desc": "城市",
        "auth": "wennn",
    },
    MD_TAX_RATE_LIST: {
        "url": "/system/lookup/selectMdTaxRateForLookup",
        "method": "GET",
        "desc": "税码",
        "auth": "linzm",
    },
    SYS_MD_MEUNITFOR: {
        "url": "/system/lookup/getMdMeunitForLookup",
        "method": "GET",
        "desc": "计量单位",
        "auth": "huangh",
    },
    MD_BRAND_LIST: {
        "url": "/system/lookup/selectMdBrandForLookup",
        "method": "GET",
        "auth": "wu_jw",
        "desc": "品牌LookUp",
        "mockhandler": "list",
        "mocktable": "md_brand",
    },
    MD_PRODLINE_LIST: {
        "url": "/system/lookup/selectMdProdLineForLookup",
        "method": "GET",
        "auth": "wu_jw",
        "desc": "产品线ookUp",
        "mockhandler": "list",
        "mocktable": "MD_ENTITY_LIST",
    },
    BC_VEHICLE_LIST: {
        "url": "/system/lookup/searchVehicleForLookup",
        "method": "GET",
        "auth": "wu_jw",
        "desc": "查询交通工具舱位ookUp",
        "mockhandler": "list",
        "mocktable": "BC_VEHICLE",
    },
    BC_VEHICLE_SEAT_LIST: {
        "url": "/system/lookup/searchVehicleSeatForLookup",
        "method": "GET",
        "auth": "wu_jw",
        "desc": "查询交通工具舱位ookUp",
        "mockhandler": "list",
        "mocktable": "BC_VEHICLE_SEAT",
    },
    BD_PERIOD_LIST: {
        "url": "/system/lookup/searchPeriodForLookup",
        "method": "GET",
        "auth": "wu_jw",
        "desc": "预算期间ookUp",
    },
    BD_PERIOD_NEW_LIST: {
        "url": "/system/lookup/searchPeriodWithBdUnitForLookup",
        "method": "GET",
        "auth": "wu_jw",
        "desc": "预算期间ookUp",
    },
    CM_CONTRACT_LIST: {
        "url": "/system/lookup/queryCmContractForLookup",
        "method": "GET",
        "auth": "xia_zhh",
        "desc": "合同查询LookUp",
    },
    BC_SAP_ORDER_LIST: {
        "url": "/system/lookup/selectBcSapOrderForLookup",
        "method": "GET",
        "desc": "内部订单号",
        "auth": "tt",
    },
    DOC_NO_CODE: {
        "url": "/fsc/project/pjProject/getPjProjectByUserInfo",
        "method": "GET",
        "desc": "立项单号",
        "auth": "tt",
    },
    TYPE_CODE_LIST: {
        "url": "/system/lookup/queryRcBusinessTypeForLookup",
        "method": "GET",
        "desc": "业务大类代码",
        "auth": "linzm",
    },
    COND_EXPRESSION_LIST: {
        "url": "/system/lookup/queryRcExpressionHouseForLookup",
        "method": "GET",
        "desc": "条件表达式",
        "auth": "linzm",
    },
    EMPLOYEE_LEVEL_LIST: {
        "url": "/system/lookup/selectBcPositionLevelsForLookup",
        "method": "GET",
        "desc": "员工职务级别",
        "auth": "zhaoran",
    },
    ENTITY_NAME_LIST: {
        "url": "/system/md/mdEntity/getOrgEntitySelect",
        "method": "GET",
        "desc": "立项部门",
        "auth": "tt",
    },
    ANALYSETYPE_LIST: {// add by yuanrr
        "url": "/system/md/creditTargetType/listByDto",
        "method": "GET",
        "desc": "指标类型",
        "auth": "yuanrr",
    },
    VENDOR_LIST: {
        "url": "/system/lookup/getBcFiVendorForLookup",
        "method": "GET",
        "desc": "供应商",
        "auth": "zhaoran",
    },
    PARTNER_LIST: {
        "url": "/system/lookup/getCustomerForLookup",
        "method": "GET",
        "auth": "tt",
        "desc": "客户",
        "mockhandler": "list",
        "mocktable": "",
    },
    CM_CONT: {
        "url": "/fsc/contract/contractquery/queryCmContractList",
        "method": "GET",
        "auth": "huangh",
        "desc": "合同编号",
    },
    MD_HOUSEBANK: {
        "url": "/system/lookup/getMdHouseBankForLookup",
        "method": "GET",
        "auth": "wyh",
        "desc": "开户行/中间行",
    },
    // HANDLEURL: {
    //     "url": "/system/lookup/getRcFlowHandleUrlsForLookUp",
    //     "method": "GET",
    //     "auth": "linzm",
    //     "desc": "处理路径",
    // },


    EA_APPLY: {
        "url": "/system/lookup/searchEaApplyForLookup",
        "method": "GET",
        "auth": "huangh",
        "desc": "申请单",
    },
    EA_APPLY_TRAVEL: {
        "url": "/system/lookup/searchEaApplyForTravelLookup",
        "method": "GET",
        "auth": "wennn",
        "desc": "申请单 差旅用到",
    },
    EC_ALCA: {
        "url": "/system/lookup/queryEcAlcaForLookup",
        "method": "GET",
        "auth": "huangh",
        "desc": "待摊规则单",
    },
    FI_BL06: {
        "url": "/system/lookup/selectBcSapPkForLookup",
        "method": "GET",
        "auth": "lichunxiao",
        "desc": "记账码",
    },
    FI_BL07: {
        "url": "/system/lookup/selectBcSapPayConditionForLookup",
        "method": "GET",
        "auth": "lichunxiao",
        "desc": "付款条件",
    },
    FI_BL08: {
        "url": "/system/lookup/selectBcFiAccountForLookup",
        "method": "GET",
        "auth": "lichunxiao",
        "desc": "总账科目",
    },
    VE_CONDITION: {
        "url": "/system/lookup/queryVgPostingConditionForLookup",
        "method": "GET",
        "auth": "linzm",
        "desc": "条件描述",
    },
    VE_RCBUSINESSDATAELEMENT: {
        "url": "/system/lookup/queryRcBusinessDataElementList",
        "method": "GET",
        "auth": "linzm",
        "desc": "凭证分录--查询单据值",
    },
    BC_SAPSQL: {
        "url": "/system/lookup/searchBcSapSglForLookup",
        "method": "GET",
        "auth": "linzm",
        "desc": "特殊总账",
    },
    REASON: {
        "url": "/system/lookup/searchBcSapReasonForLookup",
        "method": "GET",
        "auth": "linzm",
        "desc": "原因代码",
    },
    BC_SAPVOUCHERTYPE: {
        "url": "/system/lookup/searchBcSapVoucherTypeForLookup",
        "method": "GET",
        "auth": "linzm",
        "desc": "凭证类型",
    },

    WT_RATE: {
        "url": "/system/lookup/searchMdWtRateForLookup",
        "method": "GET",
        "auth": "zhaoran",
        "desc": "WT税码lookup",
    },
    CHANNEL_LIST: {
        "url": "/system/lookup/getMdChannelForLookup",
        "method": "GET",
        "auth": "tt",
        "desc": "渠道lookup",
    },
    LANGUAGE: {
        "url": "/system/lookup/searchMdLanguageForLookup",
        "method": "GET",
        "auth": "linzm",
        "desc": "语言",
    },
    SELECTUSER: {
        "url": "/system/lookup/selectUserInfoForLookup",
        "method": "GET",
        "auth": "linzm",
        "desc": "语言",
    },
    BCSAPMATERIAL: {
        "url": "/system/lookup/searchBcSapMaterialForLookup",
        "method": "GET",
        "auth": "linzm",
        "desc": "物料号",
    },
    BC_ECITEM_ACCOUNTLIST: {
        "url": "/system/lookup/getBcEcItemAccountLookup",
        "method": "GET",
        "desc": "报账项目（费用项目）",
        "auth": "huangh",
    },
    WP_BUSSINESS_APP: {
        "url": "/wp/basic/businessApplication/list",
        "method": "GET",
        "desc": "业务系统",
        "auth": "hxl",
    },
    WP_BUSSINESSTYPE_APP: {
        "url": "/wp/basic/businessType/list",
        "method": "GET",
        "desc": "业务大类",
        "auth": "hxl",
    },
    WP_DOCTYPE_APP: {
        "url": "/wp/basic/docType/list",
        "method": "GET",
        "desc": "单据类型",
        "auth": "hxl",
    },
    SYSTEM_GET_MDCORP: {
        "url": "/system/lookup/getMdCorpForLookupSelect",
        "method": "GET",
        "desc": "结算单位",
        "auth": "hxl",
    },
    VOUCHERTEMPLATE_VOUCHERELEMENT: {
        "url": "/system/lookup/queryVgVoucherElementList",
        "method": "GET",
        "desc": "凭证模板--查询凭证要素",
        "auth": "linzm",
    },
    VOUCHERTEMPLATE_FUNCLIST: {
        "url": "/system/lookup/queryRcRuleFuncList",
        "method": "GET",
        "desc": "凭证模板--查询函数",
        "auth": "linzm",
    },
    VOUCHERTEMPLATE_BUSDATAPARTS: {
        "url": "/system/lookup/queryBusinessDataPartsForLookup",
        "method": "GET",
        "desc": "凭证模板--查询数据来源",
        "auth": "linzm",
    },
    ACCOUNT_FOR_VOUCHER: {
        "url": "/system/lookup/selectBcFiAccountForLookup",
        "method": "GET",
        "desc": "记账账户--会计科目",
        "auth": "linzm",
    },
    VENDOR_FOR_VOUCHER: {
        "url": "/system/lookup/queryBcFiVendorForLookup",
        "method": "GET",
        "desc": "记账账户--供应商",
        "auth": "linzm",
    },
    CUSTOMER_FOR_VOUCHER: {
        "url": "/system/lookup/queryBcFiCustomerForLookup",
        "method": "GET",
        "desc": "记账账户--客户",
        "auth": "linzm",
    },
    ASSET_FOR_VOUCHER: {
        "url": "/system/lookup/queryBcFiAssetForLookup",
        "method": "GET",
        "desc": "记账账户--资产号",
        "auth": "linzm",
    },
    WP_DISPATCH_NODE: {
        "url": "/wp/basic/dispatchNode/list",
        "method": "GET",
        "desc": "派工节点",
        "auth": "hxl",
    },
    WP_FSSCENTERUNIT_SELECT: {
        "url": "/wp/basic/fssCenterUnit/selectByFscId",
        "method": "GET",
        "desc": "业务系统-共享中心",
        "auth": "hxl",
    },
    USER_SHARE_CENTER: {
        "url": "/userInfo/listByDto",
        "method": "GET",
        "desc": "共享中心-用户列表",
        "auth": "hxl",
    },
    FM_FS_CASH_PROJECT: {
        "url": "/system/lookup/searchMdCashFlowForLookup",
        "method": "GET",
        "auth": "wyh",
        "desc": "现金流量项目",
    },
    PAYFLOW_CORP: {
        "url": "/system/md/corp/selectPageOrderMap",
        "method": "GET",
        "auth": "linzm",
        "desc": "资金流程分配--结算单位",
    },
    MD_PAYMENTER_LOOKUP: {
        "url": "/system/lookup/getMdCorpForLookupWithDataRule",
        "method": "GET",
        "auth": "why",
        "desc": "资金支付使用 付款方 结算公司",
    },
    MD_PAYEE_LOOKUP: {
        "url": "/system/lookup/getMdPartnerForLookUpWithDataRule",
        "method": "GET",
        "auth": "why",
        "desc": "资金支付使用 收款方 供应商",
    },
    MD_EMPLOYEE_LOOKUP: {
        "url": "/system/lookup/selectUserInfoForLookupWithDataRule",
        "method": "GET",
        "auth": "why",
        "desc": "资金支付使用 员工 用户",
    },
    REIM_UNIT_NAME: {
        "url": "/system/lookup/getMdEntityUnitSelect",
        "method": "GET",
        "auth": "linzm",
        "desc": "报账单查询 报账公司",
    },
    UserInfo: {
        "url": "/system/lookup/selectUserInfo",
        "method": "GET",
        "auth": "zhaoran",
        "desc": "公司下所有员工",
    },

}